In [2]:
import numpy as np

In [ ]:
#Numpy Arrays
#1D vectors or 2D matrices

In [3]:
#Casting normal python list into an array
my_list=[1,2,3,4]
arr = np.array(my_list)
arr

array([1, 2, 3, 4])

In [4]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
#Generating arrays
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones((2,3)) #Pass in a tuple for 2D array/matrix


array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.linspace(0,5,5) #returns a 1D vector with equally spaced numbers in the given range

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.random.rand(5) #returns a 1D array of random numbers from uniform distribution of 0-1

array([0.06800841, 0.23703136, 0.01621009, 0.91563367, 0.23547678])

In [14]:
np.random.randn(2) #returns a 1D array of random numbers from a standard normal curve 

array([1.73486618, 0.73363051])

In [17]:
np.random.randint(1,101,10) #returns random integers from a low to a high number(lowest inclusive and highest exclusive)
                         #We can also pass in the number of random integers we want

array([47, 68, 87, 59, 61, 59, 20, 60, 78, 61])

In [19]:
random_array=np.random.randint(0,50,10)
random_array

array([38, 30, 17, 27,  0, 23,  6, 29, 27,  1])

In [21]:
random_array.reshape(5,2) #We can reshape the array by calling the reshape method on the array

array([[38, 30],
       [17, 27],
       [ 0, 23],
       [ 6, 29],
       [27,  1]])

In [22]:
random_array.max() #To get the maximum element in an array

38

In [24]:
random_array.argmax() #Returns the index location of the max value

4

In [29]:
random_array.shape #returns the shape of the array

(10,)

In [26]:
arr


array([1, 2, 3, 4])

In [30]:
arr.dtype #returns the actual data type in an array

dtype('int32')

In [31]:
from numpy.random import randint
randint(0,50)

26

In [40]:
#Numpy indexing and selection
arr = np.arange(0,11)
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [45]:
#numpy arrays differ from a normal python list because of their ability to broadcast
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [41]:
slice_of_array=arr[0:5]
slice_of_array

array([0, 1, 2, 3, 4])

In [44]:
slice_of_array=arr[0:6]
slice_of_array[0:4]=100
slice_of_array #the changes effect the original array

array([100, 100, 100, 100,   4,   5])

In [43]:
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [47]:
arr2=np.array([[1,3,4],[2,3,4],[4,4,5]])
arr2[1][1]

3

In [48]:
arr2[:2,1:]

array([[3, 4],
       [3, 4]])

In [49]:
bool_arr = arr > 5
bool_arr

array([ True,  True,  True,  True, False, False,  True,  True,  True,
        True,  True])

In [50]:
arr[bool_arr] #conditionally selects the elements which are True

array([100, 100, 100, 100,   6,   7,   8,   9,  10])

In [52]:
#Numpy Operations
#Array with array
#Array with scalars
#Universal array functions
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [54]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [55]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [68]:
#To get the sum of all the elements in a given column
import numpy as np
arr=np.arange(0,50,10)
arr.shape

(5,)

In [ ]:
import pandas as pd
sal = pd.read_csv('Salaries.csv')
sal.head(2) #2 rows
sal.info() #the number of clmns and base entries
sal['BasePay'].mean()
sal['OvertimePay'].max()
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['JobTitle'] #returns specific data
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['TotalPayBenefits']
#Find name of highest paid person(including benefits)
sal[sal['TotalPayBenefits'] ==sal['TotalPayBenefits'].max()]['EmployeeName']
#OR
sal.loc[sal['TotalPayBenefits'].idxmax()]
#OR
sal.iloc[sal['TotalPayBenefits'].argmax()]
#Find average BasePay of all employees per year(2011-2014)
sal.groupby('Year').mean()['BasePay']
#How many unique job titles are there
sal['JobTitle'].nunique()
#Top 5 most common jobs
sal['JobTitle'].value_counts().head(5)
#Job titles with only one occurence in 2013
sum(sal[sal['Year']==2013]['JobTitle'].value_counts() == 1)
#How many people have the word Cheif in their job title
def chief_string(title):
    if 'chief' in title.lower().split():
        return True
    else:
        return False
######################
sum(sal['JobTitle'].apply(lambda x: chief_string(x))) #returns the sum
#Is there a correlation between length of the Job Title string and Salary
sal['title_len'] = sal['JobTitle'].apply(len)
sal[['TotalPayBenefits','title_len']].corr()


In [ ]:
#Import pandas and read in the Ecommerce Purchases csv file and set it to a DataFrame
#called ecom
import pandas as pd
ecom = pd.read_csv('Ecommerce Purchases')
ecom.head()
#number of rows and columns
len(ecom.columns)
len(ecom.index) #no.of rows
ecom.info()
#What is the average purchase price
ecom['Purchase Price'].mean()
ecom['Purchase Price'].max()
#How many people have English 'en' as their Language of choice on the website
ecom[ecom['Language']=='en']['Language'].count()
#How many people have the job title of "Lawyer"
ecom[ecom['Job']=='Lawyer'].count()
#OR
len(ecom[ecom['Job']=='Lawyer'].index)
#How many people purchased during the AM or PM
ecom['AM or PM'].value_counts()
#What are the 5 most common Job Titles
ecom['Job'].value_counts().head(5) #value_counts automatically sorts the most popular counts
#Someone made a purchase that came from Lot:"90 WT", what was the Purchase Price for this transaction
ecom[ecom['Lot']=='90 WT']['Purchase Price']
#What is the email of the person with the following Credit Card Number:45365474546547
ecom[ecom['Credit Card']==45365474546547]['Email']
#How many people have American Express as their Credit Card Provider and made a purchase above $95
ecom[(ecom['CC Provider']=='American Express') & (ecom['Purchase Price']>95) ].count()
#How many people have a credit card that expires in 2025
ecom[ecom['CC Exp Date'].apply(lambda exp: exp[3:]=='25')].count()
#What are the top 5 most popular email provider/hosts
ecom['Email'].apply(lambda email: email.split('@')[1]).value_counts().head(5)

